// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqipy3u1DzNCKIzFYoFAuV85cHEDOmaSQ',
    appId: '1:345923835537:android:2927f359ca111f6a3c9130',
    messagingSenderId: '345923835537',
    projectId: 'tnerserver',
    storageBucket: 'tnerserver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAplIum-t1zwZI_Dr0up_iWyTyFhxfsP3s',
    appId: '1:345923835537:ios:0d4ee2f2860dd45a3c9130',
    messagingSenderId: '345923835537',
    projectId: 'tnerserver',
    storageBucket: 'tnerserver.appspot.com',
    androidClientId: '345923835537-6jqbhn1rkuo2kuu0m89v30p6t4b986rg.apps.googleusercontent.com',
    iosClientId: '345923835537-ffs7ppumkok7dt244vo28t773ofdr8mf.apps.googleusercontent.com',
    iosBundleId: 'com.tner.tnerClient',
  );
}
